name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry & Nox
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox

      - name: Run lint
        run: nox -s lint

      - name: Run tests
        run: nox -s tests
